@echo off
echo Starting Bokea App...
start /b dotnet run
echo Waiting for the server to start...
timeout /t 3 /nobreak > nul
echo Opening http://localhost:5233 in your browser...
start http://localhost:5233
